apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/appdb
---
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: prod
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/appdb
